-- Sementes de Produtos Ampliadas (200 Produtos mais comuns, sem bebidas alcoólicas)
USE lista_supermercados;

-- 1. Garante que todas as categorias necessárias existam
INSERT IGNORE INTO categories (name) VALUES
('Mercearia'),
('Hortifruti'),
('Carnes & Peixes'),
('Laticínios & Frios'),
('Bebidas'),
('Limpeza'),
('Higiene & Perfumaria');

-- 2. Garante que todas as marcas comuns existam
INSERT IGNORE INTO brands (name) VALUES
('Italac'), ('Piracanjuba'), ('Elegê'), ('Vigor'), ('Danone'), ('Itambé'), ('Tirolez'), ('Catupiry'),
('Tio João'), ('Camil'), ('Kicaldo'), ('Yoki'), ('Renata'), ('Barilla'), ('Dona Benta'), ('Nissin'),
('Liza'), ('Soya'), ('Gallo'), ('Borges'), ('Pilão'), ('Melitta'), ('Nescafé'), ('3 Corações'), ('Mate Leão'),
('Nescau'), ('Toddy'), ('Ninho'), ('Molico'), ('Quaker'), ('Kellogg\'s'),
('Pomarola'), ('Heinz'), ('Elefante'), ('Hellmann\'s'), ('Arisco'), ('Sazón'), ('Knorr'), ('Cisne'),
('Quero'), ('Coqueiro'), ('Bonare'),
('Vitarella'), ('Bauducco'), ('Pringles'), ('Ruffles'), ('Doritos'),
('Sadia'), ('Seara'), ('Perdigão'), ('Friboi'), ('Swift'), ('Ceratti'), ('Copacol'),
('Coca-Cola'), ('Guaraná Antarctica'), ('Fanta'), ('Sprite'), ('Pepsi'), ('Del Valle'), ('Ades'), ('Tang'), ('Crystal'), ('Kero Coco'), ('Monster'), ('Gatorade'),
('Omo'), ('Comfort'), ('Downy'), ('Vanish'), ('Ypê'), ('Limpol'), ('Minuano'), ('Veja'), ('Pinho Sol'), ('SBP'),
('Colgate'), ('Oral-B'), ('Close-up'), ('Rexona'), ('Dove'), ('Nivea'), ('Palmolive'), ('Seda'), ('Pantene'), ('Neve'), ('Huggies'), ('Pampers'), ('Always');

-- 3. Insere a lista detalhada de produtos populares
-- MERCEARIA (Açúcar, Arroz, Feijão, Macarrão, Azeites, Óleos, Conservas, Temperos, Biscoitos)
INSERT IGNORE INTO products (ean, name, normalized_name, brand_id, category_id) VALUES
('7891234500001', 'Arroz Agulhinha Tipo 1 Camil 5kg', 'arroz agulhinha tipo 1 camil 5kg', (SELECT id FROM brands WHERE name = 'Camil'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500002', 'Arroz Integral Camil 1kg', 'arroz integral camil 1kg', (SELECT id FROM brands WHERE name = 'Camil'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500003', 'Feijão Carioca Tipo 1 Camil 1kg', 'feijao carioca tipo 1 camil 1kg', (SELECT id FROM brands WHERE name = 'Camil'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500004', 'Feijão Preto Tipo 1 Camil 1kg', 'feijao preto tipo 1 camil 1kg', (SELECT id FROM brands WHERE name = 'Camil'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500005', 'Feijão Carioca Kicaldo 1kg', 'feijao carioca kicaldo 1kg', (SELECT id FROM brands WHERE name = 'Kicaldo'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500006', 'Açúcar Refinado Extra União 1kg', 'acucar refinado extra uniao 1kg', (SELECT id FROM brands WHERE name = 'União'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500007', 'Açúcar Demerara União 1kg', 'acucar demerara uniao 1kg', (SELECT id FROM brands WHERE name = 'União'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500008', 'Açúcar Cristal Caravelas 1kg', 'acucar cristal caravelas 1kg', (SELECT id FROM brands WHERE name = 'Caravelas'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500009', 'Farinha de Trigo Tradicional Dona Benta 1kg', 'farinha de trigo tradicional dona benta 1kg', (SELECT id FROM brands WHERE name = 'Dona Benta'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500010', 'Farinha de Trigo Especial Renata 1kg', 'farinha de trigo especial renata 1kg', (SELECT id FROM brands WHERE name = 'Renata'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500011', 'Farinha de Mandioca Torrada Yoki 500g', 'farinha de mandioca torrada yoki 500g', (SELECT id FROM brands WHERE name = 'Yoki'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500012', 'Farinha de Milho Flocada Yoki 500g', 'farinha de milho flocada yoki 500g', (SELECT id FROM brands WHERE name = 'Yoki'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500013', 'Macarrão Espaguete 8 Renata 500g', 'macarrao espaguete 8 renata 500g', (SELECT id FROM brands WHERE name = 'Renata'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500014', 'Macarrão Sêmola Parafuso Renata 500g', 'macarrao semola parafuso renata 500g', (SELECT id FROM brands WHERE name = 'Renata'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500015', 'Macarrão Espaguete n.5 Barilla 500g', 'macarrao espaguete n 5 barilla 500g', (SELECT id FROM brands WHERE name = 'Barilla'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500016', 'Macarrão Instantâneo Nissin Miojo Galinha Caipira 85g', 'macarrao instantaneo nissin miojo galinha caipira 85g', (SELECT id FROM brands WHERE name = 'Nissin'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500017', 'Óleo de Soja Liza 900ml', 'oleo de soja liza 900ml', (SELECT id FROM brands WHERE name = 'Liza'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500018', 'Óleo de Soja Soya 900ml', 'oleo de soja soya 900ml', (SELECT id FROM brands WHERE name = 'Soya'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500019', 'Óleo de Girassol Liza 900ml', 'oleo de girassol liza 900ml', (SELECT id FROM brands WHERE name = 'Liza'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500020', 'Azeite de Oliva Extra Virgem Gallo Tipo Único 500ml', 'azeite de oliva extra virgem gallo tipo unico 500ml', (SELECT id FROM brands WHERE name = 'Gallo'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500021', 'Azeite de Oliva Extra Virgem Clássico Borges 500ml', 'azeite de oliva extra virgem classico borges 500ml', (SELECT id FROM brands WHERE name = 'Borges'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500022', 'Café em Pó Tradicional Pilão Vácuo 500g', 'cafe em po tradicional pilao vacuo 500g', (SELECT id FROM brands WHERE name = 'Pilão'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500023', 'Café em Pó Tradicional Melitta 500g', 'cafe em po tradicional melitta 500g', (SELECT id FROM brands WHERE name = 'Melitta'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500024', 'Café Solúvel Nescafé Original Granulado 100g', 'cafe soluvel nescafe original granulado 100g', (SELECT id FROM brands WHERE name = 'Nescafé'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500025', 'Chá Mate Leão Sachê Natural 25g', 'cha mate leao sache natural 25g', (SELECT id FROM brands WHERE name = 'Mate Leão'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500026', 'Achocolatado em Pó Nescau 2.0 Lata 400g', 'achocolatado em po nescau 2 0 lata 400g', (SELECT id FROM brands WHERE name = 'Nescau'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500027', 'Achocolatado em Pó Toddy Original 400g', 'achocolatado em po toddy original 400g', (SELECT id FROM brands WHERE name = 'Toddy'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500028', 'Leite em Pó Integral Instantâneo Ninho Lata 380g', 'leite em po integral instantaneo ninho lata 380g', (SELECT id FROM brands WHERE name = 'Ninho'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500029', 'Leite em Pó Desnatado Molico Lata 280g', 'leite em po desnatado molico lata 280g', (SELECT id FROM brands WHERE name = 'Molico'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500030', 'Aveia em Flocos Finos Quaker Caixa 165g', 'aveia em flocos finos quaker caixa 165g', (SELECT id FROM brands WHERE name = 'Quaker'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500031', 'Cereal Matinal Sucrilhos Kellogg\'s Original 240g', 'cereal matinal sucrilhos kellogg s original 240g', (SELECT id FROM brands WHERE name = 'Kellogg\'s'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500032', 'Molho de Tomate Tradicional Pomarola Sachê 300g', 'molho de tomate tradicional pomarola sache 300g', (SELECT id FROM brands WHERE name = 'Pomarola'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500033', 'Molho de Tomate Heinz Tradicional Sachê 300g', 'molho de tomate heinz tradicional sache 300g', (SELECT id FROM brands WHERE name = 'Heinz'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500034', 'Extrato de Tomate Elefante Pote 310g', 'extrato de tomate elefante pote 310g', (SELECT id FROM brands WHERE name = 'Elefante'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500035', 'Ketchup Heinz Tradicional Pet 397g', 'ketchup heinz tradicional pet 397g', (SELECT id FROM brands WHERE name = 'Heinz'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500036', 'Mostarda Heinz Tradicional Pet 255g', 'mostarda heinz tradicional pet 255g', (SELECT id FROM brands WHERE name = 'Heinz'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500037', 'Maionese Tradicional Hellmann\'s Pote 500g', 'maionese tradicional hellmann s pote 500g', (SELECT id FROM brands WHERE name = 'Hellmann\'s'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500038', 'Sal Refinado Extra Cisne 1kg', 'sal refinado extra cisne 1kg', (SELECT id FROM brands WHERE name = 'Cisne'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500039', 'Tempero Pronto Sazón Vermelho Carnes 60g', 'tempero pronto sazon vermelho carnes 60g', (SELECT id FROM brands WHERE name = 'Sazón'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500040', 'Caldo de Galinha Knorr Tabletes 57g', 'caldo de galinha knorr tabletes 57g', (SELECT id FROM brands WHERE name = 'Knorr'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500041', 'Milho Verde Quero Lata 170g', 'milho verde quero lata 170g', (SELECT id FROM brands WHERE name = 'Quero'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500042', 'Ervilha em Conserva Quero Lata 170g', 'ervilha em conserva quero lata 170g', (SELECT id FROM brands WHERE name = 'Quero'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500043', 'Sardinha em Óleo Coqueiro Lata 125g', 'sardinha em oleo coqueiro lata 125g', (SELECT id FROM brands WHERE name = 'Coqueiro'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500044', 'Atum Ralado ao Natural Coqueiro Lata 170g', 'atum ralado ao natural coqueiro lata 170g', (SELECT id FROM brands WHERE name = 'Coqueiro'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500045', 'Seleta de Legumes Bonare Lata 170g', 'seleta de legumes bonare lata 170g', (SELECT id FROM brands WHERE name = 'Bonare'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500046', 'Biscoito Recheado Passatempo Leite 130g', 'biscoito recheado passatempo leite 130g', (SELECT id FROM brands WHERE name = 'Nestlé'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500047', 'Biscoito Recheado Negresco Chocolate 140g', 'biscoito recheado negresco chocolate 140g', (SELECT id FROM brands WHERE name = 'Nestlé'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500048', 'Biscoito Cream Cracker Vitarella 400g', 'biscoito cream cracker vitarella 400g', (SELECT id FROM brands WHERE name = 'Vitarella'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500049', 'Biscoito Água e Sal Renata Pacote 360g', 'biscoito agua e sal renata pacote 360g', (SELECT id FROM brands WHERE name = 'Renata'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500050', 'Mini Bolo Recheado Bauducco Chocolate 40g', 'mini bolo recheado bauducco chocolate 40g', (SELECT id FROM brands WHERE name = 'Bauducco'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500051', 'Batata Frita Lisa Ruffles Original 76g', 'batata frita lisa ruffles original 76g', (SELECT id FROM brands WHERE name = 'Ruffles'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500052', 'Tortilha Chips Doritos Queijo Nacho 140g', 'tortilha chips doritos queijo nacho 140g', (SELECT id FROM brands WHERE name = 'Doritos'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500053', 'Pipoca Yoki Premium 500g', 'pipoca yoki premium 500g', (SELECT id FROM brands WHERE name = 'Yoki'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500054', 'Bolo de Caneca Yoki Chocolate 70g', 'bolo de caneca yoki chocolate 70g', (SELECT id FROM brands WHERE name = 'Yoki'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500055', 'Sal Grosso para Churrasco Cisne 1kg', 'sal grosso para churrasco cisne 1kg', (SELECT id FROM brands WHERE name = 'Cisne'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500056', 'Polpa de Tomate Quero Sachê 520g', 'polpa de tomate quero sache 520g', (SELECT id FROM brands WHERE name = 'Quero'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500057', 'Creme de Avelã Nutella Pote 350g', 'creme de avela nutella pote 350g', (SELECT id FROM brands WHERE name = 'Nestlé'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500058', 'Fermento em Pó Químico Dr Oetker 100g', 'fermento em po quimico dr oetker 100g', NULL, (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500059', 'Milho para Pipoca Micro-ondas Yoki Manteiga 100g', 'milho para pipoca micro ondas yoki manteiga 100g', (SELECT id FROM brands WHERE name = 'Yoki'), (SELECT id FROM categories WHERE name = 'Mercearia')),
('7891234500060', 'Mistura para Bolo Dona Benta Chocolate 450g', 'mistura para bolo dona benta chocolate 450g', (SELECT id FROM brands WHERE name = 'Dona Benta'), (SELECT id FROM categories WHERE name = 'Mercearia')),

-- LATICÍNIOS & FRIOS (Leites, Manteiga, Requeijão, Queijo, Presunto, Iogurtes)
('7891234500061', 'Leite UHT Integral Italac Caixa 1L', 'leite uht integral italac caixa 1l', (SELECT id FROM brands WHERE name = 'Italac'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500062', 'Leite UHT Desnatado Italac Caixa 1L', 'leite uht desnatado italac caixa 1l', (SELECT id FROM brands WHERE name = 'Italac'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500063', 'Leite UHT Integral Piracanjuba Caixa 1L', 'leite uht integral piracanjuba caixa 1l', (SELECT id FROM brands WHERE name = 'Piracanjuba'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500064', 'Leite UHT Semi-desnatado Piracanjuba Caixa 1L', 'leite uht semi desnatado piracanjuba caixa 1l', (SELECT id FROM brands WHERE name = 'Piracanjuba'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500065', 'Manteiga de Primeira Qualidade com Sal Aviação 200g', 'manteiga de primeira qualidade com sal aviacao 200g', NULL, (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500066', 'Margarina Qualy com Sal Pote 500g', 'margarina qualy com sal pote 500g', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500067', 'Margarina Claybom com Sal Pote 500g', 'margarina claybom com sal pote 500g', (SELECT id FROM brands WHERE name = 'Perdigão'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500068', 'Queijo Muçarela Fatiado Sadia 150g', 'queijo mucarela fatiado sadia 150g', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500069', 'Presunto Cozido Fatiado Sadia 150g', 'presunto cozido fatiado sadia 150g', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500070', 'Peito de Peru Cozido e Fatiado Sadia 150g', 'peito de peru cozido e fatiado sadia 150g', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500071', 'Queijo Prato Fatiado Vigor 150g', 'queijo prato fatiado vigor 150g', (SELECT id FROM brands WHERE name = 'Vigor'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500072', 'Queijo Ralado Parmesão Faixa Azul 50g', 'queijo ralado parmesao faixa azul 50g', (SELECT id FROM brands WHERE name = 'Vigor'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500073', 'Creme de Leite Nestlé Caixinha 200g', 'creme de leite nestle caixinha 200g', (SELECT id FROM brands WHERE name = 'Nestlé'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500074', 'Creme de Leite Piracanjuba Caixinha 200g', 'creme de leite piracanjuba caixinha 200g', (SELECT id FROM brands WHERE name = 'Piracanjuba'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500075', 'Leite Condensado Moça Nestlé Semidesnatado Lata 395g', 'leite condensado moca nestle semidesnatado lata 395g', (SELECT id FROM brands WHERE name = 'Nestlé'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500076', 'Leite Condensado Piracanjuba Semidesnatado Caixinha 395g', 'leite condensado piracanjuba semidesnatado caixinha 395g', (SELECT id FROM brands WHERE name = 'Piracanjuba'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500077', 'Requeijão Cremoso Poços de Caldas Copo 200g', 'requeijao cremoso pocos de caldas copo 200g', (SELECT id FROM brands WHERE name = 'Vigor'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500078', 'Requeijão Cremoso Tradicional Vigor Copo 200g', 'requeijao cremoso tradicional vigor copo 200g', (SELECT id FROM brands WHERE name = 'Vigor'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500079', 'Iogurte Grego Tradicional Vigor Copo 90g', 'iogurte grego tradicional vigor copo 90g', (SELECT id FROM brands WHERE name = 'Vigor'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500080', 'Iogurte Natural Integral Danone Copo 170g', 'iogurte natural integral danone copo 170g', (SELECT id FROM brands WHERE name = 'Danone'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500081', 'Petit Suisse Morango Danoninho Bandeja 320g', 'petit suisse morango danoninho bandeja 320g', (SELECT id FROM brands WHERE name = 'Danone'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500082', 'Mortadela Fatiada Ceratti Copo 100g', 'mortadela fatiada ceratti copo 100g', (SELECT id FROM brands WHERE name = 'Ceratti'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500083', 'Salame Italiano Fatiado Sadia 100g', 'salame italiano fatiado sadia 100g', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500084', 'Queijo Frescal Minas Tirolez kg', 'queijo frescal minas tirolez kg', (SELECT id FROM brands WHERE name = 'Tirolez'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500085', 'Requeijão Cremoso Bisnaga Catupiry 250g', 'requeijao cremoso bisnaga catupiry 250g', (SELECT id FROM brands WHERE name = 'Catupiry'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500086', 'Queijo Parmesão Ralado Vigor Pacote 50g', 'queijo parmesao ralado vigor pacote 50g', (SELECT id FROM brands WHERE name = 'Vigor'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500087', 'Manteiga Extra com Sal Elegê Pote 200g', 'manteiga extra com sal elege pote 200g', (SELECT id FROM brands WHERE name = 'Elegê'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500088', 'Iogurte com Polpa de Morango Itambé 1kg', 'iogurte com polpa de morango itambe 1kg', (SELECT id FROM brands WHERE name = 'Itambé'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500089', 'Leite Fermentado Yakult Frasco 6x80g', 'leite fermentado yakult frasco 6x80g', NULL, (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500090', 'Queijo Provolone Fatiado Sadia 150g', 'queijo provolone fatiado sadia 150g', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500091', 'Bebida Láctea Achocolatada Toddynho Caixa 200ml', 'bebida lactea achocolatada toddynho caixa 200ml', (SELECT id FROM brands WHERE name = 'Toddy'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500092', 'Queijo Gorgonzola Tirolez kg', 'queijo gorgonzola tirolez kg', (SELECT id FROM brands WHERE name = 'Tirolez'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500093', 'Ricota Fresca de Leite Tirolez kg', 'ricota fresca de leite tirolez kg', (SELECT id FROM brands WHERE name = 'Tirolez'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500094', 'Queijo de Coalho para Churrasco Tirolez 350g', 'queijo de coalho para churrasco tirolez 350g', (SELECT id FROM brands WHERE name = 'Tirolez'), (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),
('7891234500095', 'Nata Pasteurizada Tradicional Frimesa Pote 300g', 'nata pasteurizada tradicional frimesa pote 300g', NULL, (SELECT id FROM categories WHERE name = 'Laticínios & Frios')),

-- CARNES & PEIXES
('7891234500096', 'Alcatra Bovina Peça Resfriada kg', 'alcatra bovina peca resfriada kg', (SELECT id FROM brands WHERE name = 'Friboi'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500097', 'Contra Filé Bovino em Bifes kg', 'contra file bovino em bifes kg', (SELECT id FROM brands WHERE name = 'Friboi'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500098', 'Coxão Mole Bovino em Bifes kg', 'coxao mole bovino em bifes kg', (SELECT id FROM brands WHERE name = 'Friboi'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500099', 'Carne Moída de Patinho Friboi Bandeja 500g', 'carne moida de patinho friboi bandeja 500g', (SELECT id FROM brands WHERE name = 'Friboi'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500100', 'Costela Bovina Ripada para Churrasco kg', 'costela bovina ripada para churrasco kg', (SELECT id FROM brands WHERE name = 'Friboi'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500101', 'Acém Bovino em Pedaço kg', 'acem bovino em pedaco kg', (SELECT id FROM brands WHERE name = 'Friboi'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500102', 'Filet Mignon Bovino Limpo kg', 'filet mignon bovino limpo kg', (SELECT id FROM brands WHERE name = 'Swift'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500103', 'Maminha Bovina a Vácuo kg', 'maminha bovina a vacuo kg', (SELECT id FROM brands WHERE name = 'Friboi'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500104', 'Peito de Frango sem Osso Congelado Sadia Pacote 1kg', 'peito de frango sem osso congelado sadia pacote 1kg', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500105', 'Coxa e Sobrecoxa de Frango Congelada Sadia Pacote 1kg', 'coxa e sobrecoxa de frango congelada sadia pacote 1kg', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500106', 'Filezinho de Frango Sassami Seara Pacote 1kg', 'filezinho de frango sassami seara pacote 1kg', (SELECT id FROM brands WHERE name = 'Seara'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500107', 'Frango Inteiro Congelado kg', 'frango inteiro congelado kg', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500108', 'Coração de Frango Bandeja Congelado Sadia 1kg', 'coracao de frango bandeja congelado sadia 1kg', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500109', 'Linguiça Toscana para Churrasco Seara Pacote 1kg', 'linguica toscana para churrasco seara pacote 1kg', (SELECT id FROM brands WHERE name = 'Seara'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500110', 'Linguiça Calabresa Defumada Sadia Pacote 400g', 'linguica calabresa defumada sadia pacote 400g', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500111', 'Salsicha Hot Dog Perdigão Pacote 500g', 'salsicha hot dog perdigao pacote 500g', (SELECT id FROM brands WHERE name = 'Perdigão'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500112', 'Costelinha de Porco Resfriada kg', 'costelinha de porco resfriada kg', (SELECT id FROM brands WHERE name = 'Seara'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500113', 'Pernil de Porco em Cubos Swift Pacote 1kg', 'pernil de porco em cubos swift pacote 1kg', (SELECT id FROM brands WHERE name = 'Swift'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500114', 'Bacon em Cubos Seara Pacote 200g', 'bacon em cubos seara pacote 200g', (SELECT id FROM brands WHERE name = 'Seara'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500115', 'Lombo Suíno Resfriado Pedaço kg', 'lombo suino resfriado pedaco kg', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500116', 'Filé de Tilápia Congelado Copacol Pacote 400g', 'file de tilapia congelado copacol pacote 400g', (SELECT id FROM brands WHERE name = 'Copacol'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500117', 'Filé de Merluza Congelado Copacol Pacote 500g', 'file de merluza congelado copacol pacote 500g', (SELECT id FROM brands WHERE name = 'Copacol'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500118', 'Postas de Cação Congeladas Copacol Pacote 1kg', 'postas de cacao congeladas copacol pacote 1kg', (SELECT id FROM brands WHERE name = 'Copacol'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500119', 'Hambúrguer Bovino Tradicional Sadia Caixa 672g', 'hamburguer bovino tradicional sadia caixa 672g', (SELECT id FROM brands WHERE name = 'Sadia'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),
('7891234500120', 'Cupim Bovino para Assar Swift kg', 'cupim bovino para assar swift kg', (SELECT id FROM brands WHERE name = 'Swift'), (SELECT id FROM categories WHERE name = 'Carnes & Peixes')),

-- HORTIFRUTI (Legumes e Frutas)
('7891234500121', 'Batata Monalisa Lavada kg', 'batata monalisa lavada kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500122', 'Cebola Nacional Granel kg', 'cebola nacional granel kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500123', 'Tomate Italiano Comercial kg', 'tomate italiano comercial kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500124', 'Cenoura Especial Selecionada kg', 'cenoura especial selecionada kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500125', 'Chuchu Verde Selecionado kg', 'chuchu verde selecionado kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500126', 'Abobrinha Italiana kg', 'abobrinha italiana kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500127', 'Pimentão Verde Especial kg', 'pimentao verde especial kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500128', 'Alho Roxo Pacote 200g', 'alho roxo pacote 200g', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500129', 'Alface Crespa Higienizada Unidade', 'alface crespa higienizada unidade', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500130', 'Couve Manteiga Picada Maço', 'couve manteiga picada maco', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500131', 'Rúcula Fresca Hidropônica Maço', 'rucula fresca hidroponica maco', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500132', 'Brócolis Ninja Especial Unidade', 'brocolis ninja especial unidade', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500133', 'Banana Prata Paulista kg', 'banana prata paulista kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500134', 'Maçã Gala Nacional Selecionada kg', 'maca gala nacional selecionada kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500135', 'Laranja Pêra para Suco kg', 'laranja pera para suco kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500136', 'Limão Taiti Selecionado kg', 'limao taiti selecionado kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500137', 'Mamão Papaia Selecionado kg', 'mamao papaia selecionado kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500138', 'Melancia Inteira Comum kg', 'melancia inteira comum kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500139', 'Uva Itália Sem Semente Bandeja 500g', 'uva italia sem semente bandeja 500g', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500140', 'Morango Fresco Bandeja 250g', 'morango fresco bandeja 250g', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500141', 'Abacaxi Pérola Unidade', 'abacaxi perola unidade', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500142', 'Manga Palmer de Vez kg', 'manga palmer de vez kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500143', 'Mandioca Amarela Descascada Embalada kg', 'mandioca amarela descascada embalada kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500144', 'Batata Doce Roxa Especial kg', 'batata doce roxa especial kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500145', 'Abóbora Cabotiá Pedaço kg', 'abobora cabotia pedaco kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500146', 'Berinjela Roxa Especial kg', 'berinjela roxa especial kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500147', 'Repolho Verde Especial Unidade', 'repolho verde especial unidade', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500148', 'Vagem Macarrão Selecionada kg', 'vagem macarrao selecionada kg', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500149', 'Ovo Branco Tipo Grande Mantiqueira 30 Unidades', 'ovo branco tipo grande mantiqueira 30 unidades', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),
('7891234500150', 'Cheiro Verde Coentro e Cebolinha Maço', 'cheiro verde coentro e cebolinha maco', NULL, (SELECT id FROM categories WHERE name = 'Hortifruti')),

-- BEBIDAS (NÃO ALCOÓLICAS) (Refrigerantes, Sucos, Água, Energéticos)
('7891234500151', 'Refrigerante Coca-Cola Garrafa Pet 2L', 'refrigerante coca cola garrafa pet 2l', (SELECT id FROM brands WHERE name = 'Coca-Cola'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500152', 'Refrigerante Coca-Cola Sem Açúcar Garrafa Pet 2L', 'refrigerante coca cola sem acucar garrafa pet 2l', (SELECT id FROM brands WHERE name = 'Coca-Cola'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500153', 'Refrigerante Guaraná Antarctica Pet 2L', 'refrigerante guarana antarctica pet 2l', (SELECT id FROM brands WHERE name = 'Guaraná Antarctica'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500154', 'Refrigerante Fanta Laranja Pet 2L', 'refrigerante fanta laranja pet 2l', (SELECT id FROM brands WHERE name = 'Fanta'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500155', 'Refrigerante Sprite Limão Pet 2L', 'refrigerante sprite limao pet 2l', (SELECT id FROM brands WHERE name = 'Sprite'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500156', 'Refrigerante Pepsi-Cola Pet 2L', 'refrigerante pepsi cola pet 2l', (SELECT id FROM brands WHERE name = 'Pepsi'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500157', 'Suco de Uva Integral Aurora Garrafa 1L', 'suco de uva integral aurora garrafa 1l', NULL, (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500158', 'Suco Néctar Del Valle sabor Uva Caixinha 1L', 'suco nectar del valle sabor uva caixinha 1l', (SELECT id FROM brands WHERE name = 'Del Valle'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500159', 'Suco Néctar Del Valle sabor Pêssego Caixinha 1L', 'suco nectar del valle sabor pessego caixinha 1l', (SELECT id FROM brands WHERE name = 'Del Valle'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500160', 'Bebida de Soja Ades Original Caixa 1L', 'bebida de soja ades original caixa 1l', (SELECT id FROM brands WHERE name = 'Ades'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500161', 'Refresco em Pó Tang Sabor Laranja Sachê 25g', 'refresco em po tang sabor laranja sache 25g', (SELECT id FROM brands WHERE name = 'Tang'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500162', 'Água Mineral sem Gás Crystal Garrafa 500ml', 'agua mineral sem gas crystal garrafa 500ml', (SELECT id FROM brands WHERE name = 'Crystal'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500163', 'Água Mineral com Gás Crystal Garrafa 500ml', 'agua mineral com gas crystal garrafa 500ml', (SELECT id FROM brands WHERE name = 'Crystal'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500164', 'Água de Coco Kero Coco Caixinha 1L', 'agua de coco kero coco caixinha 1l', (SELECT id FROM brands WHERE name = 'Kero Coco'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500165', 'Bebida Energética Monster Energy Lata 473ml', 'bebida energetica monster energy lata 473ml', (SELECT id FROM brands WHERE name = 'Monster'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500166', 'Bebida Isotônica Gatorade sabor Tangerina Garrafa 500ml', 'bebida isotonica gatorade sabor tangerina garrafa 500ml', (SELECT id FROM brands WHERE name = 'Gatorade'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500167', 'Néctar de Fruta Del Valle sabor Maracujá Caixa 1L', 'nectar de fruta del valle sabor maracuja caixa 1l', (SELECT id FROM brands WHERE name = 'Del Valle'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500168', 'Água Tônica Antarctica Lata 350ml', 'agua tonica antarctica lata 350ml', (SELECT id FROM brands WHERE name = 'Guaraná Antarctica'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500169', 'Refrigerante Citrus Schweppes Lata 350ml', 'refrigerante citrus schweppes lata 350ml', (SELECT id FROM brands WHERE name = 'Coca-Cola'), (SELECT id FROM categories WHERE name = 'Bebidas')),
('7891234500170', 'Suco Maguary Concentrado Caju Garrafa 500ml', 'suco maguary concentrado caju garrafa 500ml', NULL, (SELECT id FROM categories WHERE name = 'Bebidas')),

-- LIMPEZA
('7891234500171', 'Lava Roupas em Pó Omo Lavagem Perfeita Caixa 1.6kg', 'lava roupas em po omo lavagem perfeita caixa 1 6kg', (SELECT id FROM brands WHERE name = 'Omo'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500172', 'Lava Roupas Líquido Omo Concentrado 3L', 'lava roupas liquido omo concentrado 3l', (SELECT id FROM brands WHERE name = 'Omo'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500173', 'Amaciante de Roupas Comfort Concentrado Original 1L', 'amaciante de roupas comfort concentrado original 1l', (SELECT id FROM brands WHERE name = 'Comfort'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500174', 'Amaciante de Roupas Downy Concentrado Brisa de Verão 1L', 'amaciante de roupas downy concentrado brisa de verao 1l', (SELECT id FROM brands WHERE name = 'Downy'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500175', 'Tira Manchas em Pó Vanish Oxi Action Pote 450g', 'tira manchas em po vanish oxi action pote 450g', (SELECT id FROM brands WHERE name = 'Vanish'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500176', 'Detergente Líquido Ypê Neutro Frasco 500ml', 'detergente liquido ype neutro frasco 500ml', (SELECT id FROM brands WHERE name = 'Ypê'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500177', 'Detergente Líquido Limpol sabor Coco Frasco 500ml', 'detergente liquido limpol sabor coco frasco 500ml', (SELECT id FROM brands WHERE name = 'Limpol'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500178', 'Sabão em Barra Glicerinado Ypê Neutro Pacote 5x200g', 'sabao em barra glicerinado ype neutro pacote 5x200g', (SELECT id FROM brands WHERE name = 'Ypê'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500179', 'Esponja Multiuso Clássica Scotch-Brite Leve 4 Pague 3', 'esponja multiuso classica scotch brite leve 4 pague 3', NULL, (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500180', 'Limpador Multi-Uso Veja Perfumado Original 500ml', 'limpador multi uso veja perfumado original 500ml', (SELECT id FROM brands WHERE name = 'Veja'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500181', 'Desinfetante Pinho Sol sabor Limão Garrafa 1L', 'desinfetante pinho sol sabor limao garrafa 1l', (SELECT id FROM brands WHERE name = 'Pinho Sol'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500182', 'Álcool Líquido Hidratado 70% Itaquá Garrafa 1L', 'alcool liquido hidratado 70 itaqua garrafa 1l', NULL, (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500183', 'Inseticida Aerossol SBP Multi Base Água 450ml', 'inseticida aerossol sbp multi base agua 450ml', (SELECT id FROM brands WHERE name = 'SBP'), (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500184', 'Limpador Desinfetante de Banheiro Harpic Cloro Ativo 500ml', 'limpador desinfetante de banheiro harpic cloro ativo 500ml', NULL, (SELECT id FROM categories WHERE name = 'Limpeza')),
('7891234500185', 'Lava Roupas em Pó Brilhante Limpeza Total Caixa 1.6kg', 'lava roupas em po brilhante limpeza total caixa 1 6kg', NULL, (SELECT id FROM categories WHERE name = 'Limpeza')),

-- HIGIENE & PERFUMARIA
('7891234500186', 'Creme Dental Colgate Total 12 Gengivas Saudáveis 90g', 'creme dental colgate total 12 gengivas saudaveis 90g', (SELECT id FROM brands WHERE name = 'Colgate'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500187', 'Creme Dental Oral-B Pro-Saúde Prevenção Total 90g', 'creme dental oral b pro saude prevencao total 90g', (SELECT id FROM brands WHERE name = 'Oral-B'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500188', 'Enxaguante Bucal Colgate Plax Fresh Mint Zero Álcool 500ml', 'enxaguante bucal colgate plax fresh mint zero alcool 500ml', (SELECT id FROM brands WHERE name = 'Colgate'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500189', 'Escova Dental Colgate Classic Macia Leve 3 Pague 2', 'escova dental colgate classic macia leve 3 pague 2', (SELECT id FROM brands WHERE name = 'Colgate'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500190', 'Sabonete em Barra Dove Beauty Bar Original 90g', 'sabonete em barra dove beauty bar original 90g', (SELECT id FROM brands WHERE name = 'Dove'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500191', 'Sabonete em Barra Rexona sabor Bamboo Sabonete 84g', 'sabonete em barra rexona sabor bamboo sabonete 84g', (SELECT id FROM brands WHERE name = 'Rexona'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500192', 'Sabonete Líquido Palmolive Nutri-Milk Frasco 250ml', 'sabonete liquido palmolive nutri milk frasco 250ml', (SELECT id FROM brands WHERE name = 'Palmolive'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500193', 'Desodorante Antitranspirante Aerossol Rexona Men Active 150ml', 'desodorante antitranspirante aerossol rexona men active 150ml', (SELECT id FROM brands WHERE name = 'Rexona'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500194', 'Desodorante Antitranspirante Aerossol Dove Original 150ml', 'desodorante antitranspirante aerossol dove original 150ml', (SELECT id FROM brands WHERE name = 'Dove'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500195', 'Shampoo Seda Ceramidas Frasco 325ml', 'shampoo seda ceramidas frasco 325ml', (SELECT id FROM brands WHERE name = 'Seda'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500196', 'Condicionador Seda Ceramidas Frasco 325ml', 'condicionador seda ceramidas frasco 325ml', (SELECT id FROM brands WHERE name = 'Seda'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500197', 'Shampoo Pantene Pro-V Restauração Frasco 400ml', 'shampoo pantene pro v restauracao frasco 400ml', (SELECT id FROM brands WHERE name = 'Pantene'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500198', 'Condicionador Pantene Pro-V Restauração Frasco 400ml', 'condicionador pantene pro v restauracao frasco 400ml', (SELECT id FROM brands WHERE name = 'Pantene'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500199', 'Papel Higiênico Neve Folha Dupla Pacote 12 Rolos', 'papel higienico neve folha dupla pacote 12 rolos', (SELECT id FROM brands WHERE name = 'Neve'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500200', 'Lenços Umedecidos Huggies Tripla Proteção Pacote 48 Unidades', 'lencos umedecidos huggies tripla protecao pacote 48 unidades', (SELECT id FROM brands WHERE name = 'Huggies'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500201', 'Fralda Descartável Pampers Confort Sec Tamanho G 60 Unidades', 'fralda descartavel pampers confort sec tamanho g 60 unidades', (SELECT id FROM brands WHERE name = 'Pampers'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500202', 'Absorvente Higiênico Always Super Proteção com Abas 8 Unidades', 'absorvente higienico always super protecao com abas 8 unidades', (SELECT id FROM brands WHERE name = 'Always'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500203', 'Hastes Flexíveis Johnson & Johnson Cotonetes Caixa 75 Unidades', 'hastes flexiveis johnson johnson cotonetes caixa 75 unidades', NULL, (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500204', 'Protetor Solar Nivea Sun FPS 30 Frasco 200ml', 'protetor solar nivea sun fps 30 frasco 200ml', (SELECT id FROM brands WHERE name = 'Nivea'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria')),
('7891234500205', 'Creme Hidratante Corporal Nivea Milk Pele Extra Seca 400ml', 'creme hidratante corporal nivea milk pele extra seca 400ml', (SELECT id FROM brands WHERE name = 'Nivea'), (SELECT id FROM categories WHERE name = 'Higiene & Perfumaria'));
